### ISSUE TITLE
Is there any way to support group?

### ISSUE THREAD

**Issue by SolardiaX** [bmf-san/goblin#93]
Such like GIN, group can quickly create sub routers for modules with same middlewares. Is there any way to support group or just in feature? 

For eg.:
```go
r := goblin.NewRouter()
group :=r.Group("/module1")
group.Use(someMiddlwareOnlyForThisGroup)

group.Methods(http.MethodGet).Handler("/freeAPI", ...)
group.Methods(http.MethodGet).Use(Authenticator).Handler("/secretAPI", ...)
```

**Comment by bmf-san** [comment]
@SolardiaX 

Thank you for submitting your Issue!
Currently does not provide group feature.
Though I had considered that it would be better to have it as a router feature, I have not implemented it as a priority because I did not think it would be highly necessary.

I will consider implementing it at this time.
If you have a good implementation, you may send me a PR!

**Comment by bmf-san** [comment]
I considered implementing the Group, but decided not to support the conclusion. 🙏 

The reasons are as follows
- Group is not an essential feature of HTTP Router
  - Group is a convenience feature for developers and not an essential feature of HTTP Router.
  - Since goblin wants to keep the implementation as lightweight as possible, supporting this feature is against that policy and will be abandoned
- It is possible to reproduce the functionality of a pseudo-Group on the developer side.
  - Even if HTTP Router does not have Group functionality, it would be possible for HTTP Router users to reproduce the functionality equivalent to Group
   - For example, defining a list for each Group, calling the routing process in a loop, preparing a Router wrapper, etc.

I know the popular HTTP Router supports Group functionality, but I would like to hold off on supporting it in goblin for now.

If you have any attractive suggestions that we should introduce, please let me know :D
